name: Update User Table

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Show file contents
        run: cat users.json

      - name: Read users.json
        id: read-json
        run: |
          echo "::set-output name=json::$(cat users.json)"

      - name: Generate Table
        id: generate-table
        run: |
          echo "| Username | Name | Location | Company | Twitter | Followers | Private Contributions | Public Contributions |" > table.md
          echo "| -------- | ---- | -------- | ------- | ------- | --------- | -------------------- | --------------------- |" >> table.md
          
          # Parsing JSON and adding data to the table
          echo "${{ steps.read-json.outputs.json }}" | jq -r '.[] | "| \(.login) | \(.name) | \(.location) | \(.company) | \(.twitterUsername) | \(.followers) | \(.privateContributions) | \(.publicContributions) |"' >> table.md

      - name: Update README
        run: |
          cat table.md >> README.md
